<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-02-07 15:14

=======
# Generated by Django 5.1.5 on 2025-03-28 16:38

import django.db.models.deletion
from django.conf import settings
>>>>>>> 491d47c (Initial commit: Django Todo App)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 491d47c (Initial commit: Django Todo App)
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.BooleanField(default=False)),
            ],
=======
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
>>>>>>> 491d47c (Initial commit: Django Todo App)
        ),
    ]
